# Generated by Django 5.2.6 on 2025-09-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('skills', models.TextField(blank=True, verbose_name='技能')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('hire_date', models.DateField(verbose_name='入職日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在職')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
                'ordering': ['name'],
            },
        ),
    ]
