# Generated by Django 5.2.6 on 2025-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_binary',
            field=models.BinaryField(blank=True, null=True, verbose_name='員工照片二進位資料'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='照片類型'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='照片檔名'),
        ),
    ]
