# Generated by Django 5.2.6 on 2025-09-12 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_employee_photo_employee_photo_binary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(help_text='唯一的問題識別碼', max_length=50, unique=True, verbose_name='Issue ID')),
                ('test_version', models.CharField(help_text='發現問題的測試版本', max_length=100, verbose_name='測試版本')),
                ('jira_number', models.CharField(blank=True, help_text='相關的 JIRA 票號', max_length=50, verbose_name='JIRA 號碼')),
                ('project', models.CharField(help_text='相關專案名稱', max_length=200, verbose_name='Project')),
                ('script', models.TextField(blank=True, help_text='相關腳本或代碼', verbose_name='Script')),
                ('issue_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('task', 'Task'), ('support', 'Support'), ('other', 'Other')], default='bug', max_length=20, verbose_name='Issue Type')),
                ('status', models.CharField(choices=[('open', '開放中'), ('in_progress', '處理中'), ('resolved', '已解決'), ('closed', '已關閉'), ('pending', '等待中'), ('won_fix', '不修復')], default='open', max_length=20, verbose_name='修復狀態')),
                ('error_message', models.TextField(help_text='具體的錯誤訊息內容', verbose_name='錯誤訊息')),
                ('supplement', models.TextField(blank=True, help_text='額外的補充說明或解決方案', verbose_name='補充')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_issues', to=settings.AUTH_USER_MODEL, verbose_name='更新人員')),
            ],
            options={
                'verbose_name': '問題知識',
                'verbose_name_plural': '問題知識庫',
                'db_table': 'know_issue',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
