# Generated by Django 5.2.6 on 2025-09-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_knowissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('position', models.CharField(max_length=100, verbose_name='職位')),
                ('skills', models.TextField(blank=True, verbose_name='技能')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('hire_date', models.DateField(verbose_name='入職日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在職')),
                ('photo_binary', models.BinaryField(blank=True, null=True, verbose_name='員工照片二進位資料')),
                ('photo_filename', models.CharField(blank=True, max_length=255, verbose_name='照片檔名')),
                ('photo_content_type', models.CharField(blank=True, max_length=100, verbose_name='照片類型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dify員工',
                'verbose_name_plural': 'Dify員工',
                'db_table': 'dify_employee',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo_binary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo_content_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo_filename',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AlterField(
            model_name='knowissue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_issues', to='api.employee', verbose_name='更新人員'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
