# Generated by Django 5.2.6 on 2025-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_difyemployee_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowissue',
            name='issue_type',
            field=models.CharField(help_text='問題類型，如 Bug, Feature Request, Improvement 等', max_length=50, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='knowissue',
            name='status',
            field=models.CharField(help_text='狀態描述，如 開放中, 處理中, 已解決 等', max_length=50, verbose_name='修復狀態'),
        ),
    ]
