# Generated by Django 5.2.6 on 2025-09-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowissue',
            name='test_class',
            field=models.ForeignKey(blank=True, help_text='問題所屬的測試類別', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testclass', verbose_name='測試類別'),
        ),
    ]
