# Generated by Django 5.2.6 on 2025-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_knowissue_test_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowissue',
            name='class_sequence_id',
            field=models.PositiveIntegerField(blank=True, help_text='在該測試類別內的遞增ID號碼', null=True, verbose_name='類別序號'),
        ),
    ]
