# Generated by Django 5.2.6 on 2025-09-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_knowissue_class_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowissue',
            name='image1',
            field=models.ImageField(blank=True, help_text='第1張附件圖片', null=True, upload_to='know_issues/images/', verbose_name='圖片1'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image2',
            field=models.ImageField(blank=True, help_text='第2張附件圖片', null=True, upload_to='know_issues/images/', verbose_name='圖片2'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image3',
            field=models.ImageField(blank=True, help_text='第3張附件圖片', null=True, upload_to='know_issues/images/', verbose_name='圖片3'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image4',
            field=models.ImageField(blank=True, help_text='第4張附件圖片', null=True, upload_to='know_issues/images/', verbose_name='圖片4'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image5',
            field=models.ImageField(blank=True, help_text='第5張附件圖片', null=True, upload_to='know_issues/images/', verbose_name='圖片5'),
        ),
    ]
