# Generated by Django 5.2.6 on 2025-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_knowissue_image1_knowissue_image2_knowissue_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowissue',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='knowissue',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='knowissue',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='knowissue',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='knowissue',
            name='image5',
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image1_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='圖片1類型'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image1_data',
            field=models.BinaryField(blank=True, help_text='第1張附件圖片的二進制數據', null=True, verbose_name='圖片1數據'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image1_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='圖片1檔名'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image2_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='圖片2類型'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image2_data',
            field=models.BinaryField(blank=True, help_text='第2張附件圖片的二進制數據', null=True, verbose_name='圖片2數據'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image2_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='圖片2檔名'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image3_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='圖片3類型'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image3_data',
            field=models.BinaryField(blank=True, help_text='第3張附件圖片的二進制數據', null=True, verbose_name='圖片3數據'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image3_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='圖片3檔名'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image4_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='圖片4類型'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image4_data',
            field=models.BinaryField(blank=True, help_text='第4張附件圖片的二進制數據', null=True, verbose_name='圖片4數據'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image4_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='圖片4檔名'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image5_content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='圖片5類型'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image5_data',
            field=models.BinaryField(blank=True, help_text='第5張附件圖片的二進制數據', null=True, verbose_name='圖片5數據'),
        ),
        migrations.AddField(
            model_name='knowissue',
            name='image5_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='圖片5檔名'),
        ),
    ]
