# Generated by Django 5.2.6 on 2025-09-20 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_knowissue_image1_remove_knowissue_image2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, verbose_name='會話ID')),
                ('chat_type', models.CharField(choices=[('know_issue_chat', 'Know Issue Chat'), ('log_analyze_chat', 'Log Analyze Chat'), ('rvt_log_analyze_chat', 'RVT Log Analyze Chat')], max_length=50, verbose_name='聊天類型')),
                ('message_count', models.PositiveIntegerField(default=1, verbose_name='消息數量')),
                ('has_file_upload', models.BooleanField(default=False, verbose_name='是否包含文件上傳')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='響應時間(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用戶代理')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '聊天使用記錄',
                'verbose_name_plural': '聊天使用記錄',
                'db_table': 'chat_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_type', 'created_at'], name='chat_usage_chat_ty_91835e_idx'), models.Index(fields=['user', 'created_at'], name='chat_usage_user_id_c182db_idx')],
            },
        ),
    ]
