# Generated by Django 5.2.6 on 2025-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chatusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusage',
            name='chat_type',
            field=models.CharField(choices=[('know_issue_chat', 'Protocol RAG'), ('log_analyze_chat', 'AI OCR'), ('rvt_log_analyze_chat', 'RVT Log Analyze Chat')], max_length=50, verbose_name='聊天類型'),
        ),
        migrations.CreateModel(
            name='RVTGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text='文檔的唯一名稱', max_length=200, verbose_name='文檔名稱')),
                ('title', models.CharField(help_text='文檔的顯示標題', max_length=300, verbose_name='文檔標題')),
                ('version', models.CharField(default='1.0', help_text='文檔版本', max_length=50, verbose_name='版本號')),
                ('main_category', models.CharField(choices=[('system_architecture', '系統架構'), ('environment_setup', '環境準備'), ('configuration_management', '配置管理'), ('test_case_management', '測項管理'), ('operation_flow', '操作流程'), ('troubleshooting', '故障排除'), ('contact_support', '聯絡支援')], help_text='文檔所屬的主要分類', max_length=50, verbose_name='主分類')),
                ('sub_category', models.CharField(choices=[('jenkins_ansible_concept', 'Jenkins和Ansible概念'), ('system_workflow', '系統工作流程'), ('network_requirements', '網路需求'), ('hardware_requirements', '硬體設備'), ('system_installation', '系統軟體安裝'), ('bios_settings', 'BIOS設定'), ('nas_directory', 'NAS目錄結構'), ('machine_configuration', '機器設定格式'), ('group_variables', '群組變數設定'), ('required_parameters', '必要參數列表'), ('test_parameters', '測項參數說明'), ('test_modes', '測試模式'), ('test_examples', '測試範例'), ('jenkins_stages', 'Jenkins階段'), ('jenkins_operations', 'Jenkins操作'), ('uart_control', 'UART控制'), ('mdt_operations', 'MDT相關操作'), ('ansible_parameters', 'Ansible參數'), ('jenkins_failures', 'Jenkins失敗'), ('ansible_errors', 'Ansible錯誤'), ('mdt_failures', 'MDT部署失敗'), ('script_failures', '腳本執行失敗'), ('log_analysis', '日誌分析'), ('team_contacts', '團隊聯絡'), ('support_procedures', '支援流程')], help_text='文檔所屬的子分類', max_length=50, verbose_name='子分類')),
                ('content', models.TextField(help_text='文檔的主要內容', verbose_name='文檔內容')),
                ('summary', models.TextField(blank=True, help_text='文檔內容的簡要摘要', verbose_name='內容摘要')),
                ('keywords', models.CharField(blank=True, help_text='用逗號分隔的關鍵字，用於搜索優化', max_length=500, verbose_name='關鍵字')),
                ('question_type', models.CharField(choices=[('operation_guide', '操作指南'), ('parameter_explanation', '參數說明'), ('troubleshooting', '故障排除'), ('concept_explanation', '概念說明')], default='operation_guide', help_text='這個文檔主要回答什麼類型的問題', max_length=50, verbose_name='問題類型')),
                ('target_user', models.CharField(choices=[('beginner', '初學者'), ('advanced', '進階使用者'), ('admin', '系統管理員'), ('all', '所有用戶')], default='all', help_text='這個文檔的目標使用者群體', max_length=50, verbose_name='目標使用者')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發布'), ('archived', '已歸檔')], default='published', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'RVT使用指南',
                'verbose_name_plural': 'RVT使用指南',
                'db_table': 'rvt_guide',
                'ordering': ['main_category', 'sub_category', 'document_name'],
                'indexes': [models.Index(fields=['main_category', 'sub_category'], name='rvt_guide_main_ca_2ca5cc_idx'), models.Index(fields=['status', 'created_at'], name='rvt_guide_status_514545_idx')],
            },
        ),
    ]
