# Generated by Django 5.2.6 on 2025-09-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_chatusage_chat_type_rvtguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvtguide',
            name='summary',
        ),
    ]
