# Generated by Django 5.2.6 on 2025-09-21 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_summary_from_rvtguide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusage',
            name='chat_type',
            field=models.CharField(choices=[('know_issue_chat', 'Protocol RAG'), ('log_analyze_chat', 'AI OCR'), ('rvt_log_analyze_chat', 'RVT Assistant')], max_length=50, verbose_name='聊天類型'),
        ),
        migrations.CreateModel(
            name='OCRStorageBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='測試專案的名稱', max_length=200, verbose_name='專案名稱')),
                ('benchmark_score', models.IntegerField(help_text='Storage Benchmark Score', verbose_name='存儲基準分數')),
                ('average_bandwidth', models.CharField(help_text='平均帶寬 (MB/s)', max_length=50, verbose_name='平均帶寬')),
                ('device_model', models.CharField(help_text='測試裝置的型號名稱', max_length=200, verbose_name='裝置型號')),
                ('firmware_version', models.CharField(help_text='裝置韌體版本號', max_length=100, verbose_name='韌體版本')),
                ('test_datetime', models.DateTimeField(help_text='進行測試的具體時間', verbose_name='測試時間')),
                ('benchmark_version', models.CharField(help_text='3DMark 或其他基準測試軟體版本', max_length=50, verbose_name='基準版本')),
                ('read_speed', models.FloatField(blank=True, help_text='儲存裝置讀取速度', null=True, verbose_name='讀取速度 (MB/s)')),
                ('write_speed', models.FloatField(blank=True, help_text='儲存裝置寫入速度', null=True, verbose_name='寫入速度 (MB/s)')),
                ('iops_read', models.IntegerField(blank=True, help_text='每秒讀取 I/O 操作數', null=True, verbose_name='讀取IOPS')),
                ('iops_write', models.IntegerField(blank=True, help_text='每秒寫入 I/O 操作數', null=True, verbose_name='寫入IOPS')),
                ('test_environment', models.CharField(choices=[('production', '生產環境'), ('testing', '測試環境'), ('development', '開發環境'), ('benchmark', '基準測試環境')], default='benchmark', max_length=50, verbose_name='測試環境')),
                ('test_type', models.CharField(choices=[('sequential_read', '循序讀取'), ('sequential_write', '循序寫入'), ('random_read', '隨機讀取'), ('random_write', '隨機寫入'), ('mixed_workload', '混合負載'), ('comprehensive', '綜合測試')], default='comprehensive', max_length=50, verbose_name='測試類型')),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR 識別的信心度分數 (0-1)', null=True, verbose_name='OCR 信心度')),
                ('ocr_processing_time', models.FloatField(blank=True, help_text='OCR 處理所需的時間', null=True, verbose_name='OCR 處理時間 (秒)')),
                ('original_image_data', models.BinaryField(blank=True, help_text='OCR 來源圖像的二進制數據', null=True, verbose_name='原始圖像數據')),
                ('original_image_filename', models.CharField(blank=True, max_length=255, verbose_name='原始圖像檔名')),
                ('original_image_content_type', models.CharField(blank=True, max_length=100, verbose_name='原始圖像類型')),
                ('ocr_raw_text', models.TextField(blank=True, help_text='OCR 直接提取的原始文本內容', verbose_name='OCR 原始文本')),
                ('ai_structured_data', models.JSONField(blank=True, help_text='AI 處理後的結構化 JSON 資料', null=True, verbose_name='AI 結構化資料')),
                ('processing_status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '處理失敗'), ('manual_review', '需人工審核')], default='pending', max_length=30, verbose_name='處理狀態')),
                ('verification_notes', models.TextField(blank=True, help_text='人工驗證時的備註說明', verbose_name='驗證備註')),
                ('is_verified', models.BooleanField(default=False, help_text='是否經過人工驗證', verbose_name='已驗證')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ocr_records', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ocr_records', to=settings.AUTH_USER_MODEL, verbose_name='驗證人員')),
            ],
            options={
                'verbose_name': 'AI OCR 存儲基準測試',
                'verbose_name_plural': 'AI OCR 存儲基準測試',
                'db_table': 'ocr_storage_benchmark',
                'ordering': ['-test_datetime', '-created_at'],
                'indexes': [models.Index(fields=['test_datetime', 'project_name'], name='ocr_storage_test_da_b2aff7_idx'), models.Index(fields=['processing_status', 'created_at'], name='ocr_storage_process_9d7afe_idx'), models.Index(fields=['device_model', 'firmware_version'], name='ocr_storage_device__e7aee8_idx'), models.Index(fields=['is_verified', 'test_datetime'], name='ocr_storage_is_veri_5f444a_idx')],
            },
        ),
    ]
