# Generated by Django 5.2.6 on 2025-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_chatusage_chat_type_ocrstoragebenchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrstoragebenchmark',
            name='mark_version_3d',
            field=models.CharField(blank=True, help_text='3DMark 軟體的具體版本號', max_length=50, verbose_name='3DMark版本'),
        ),
    ]
