# Generated by Django 5.2.6 on 2025-09-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_mark_version_3d_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rvtguide',
            options={'ordering': ['main_category', 'sub_category', 'title'], 'verbose_name': 'RVT使用指南', 'verbose_name_plural': 'RVT使用指南'},
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='keywords',
        ),
    ]
