# Generated by Django 5.2.6 on 2025-09-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_rvtguide_options_remove_rvtguide_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='iops_read',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='iops_write',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='read_speed',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='test_environment',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='write_speed',
        ),
    ]
