# Generated by Django 5.2.6 on 2025-09-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_ocrstoragebenchmark_iops_read_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ocrstoragebenchmark',
            name='ocr_storage_process_9d7afe_idx',
        ),
        migrations.RemoveIndex(
            model_name='ocrstoragebenchmark',
            name='ocr_storage_is_veri_5f444a_idx',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='original_image_content_type',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='original_image_data',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='original_image_filename',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='ocrstoragebenchmark',
            name='verified_by',
        ),
    ]
