# Generated by Django 5.2.6 on 2025-09-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_ocrstoragebenchmark_ocr_storage_process_9d7afe_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testclass',
            table='protocol_test_class',
        ),
    ]
