# Generated by Django 5.2.6 on 2025-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_chatusage_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusage',
            name='chat_type',
            field=models.CharField(choices=[('know_issue_chat', 'Protocol RAG'), ('log_analyze_chat', 'AI OCR'), ('rvt_assistant_chat', 'RVT Assistant')], max_length=50, verbose_name='聊天類型'),
        ),
    ]
