# Generated by Django 5.2.6 on 2025-09-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_chatusage_chat_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rvtguide',
            name='rvt_guide_status_514545_idx',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='version',
        ),
    ]
