# Generated by Django 5.2.6 on 2025-09-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_rvtguide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rvtguide',
            options={'ordering': ['main_category', 'title'], 'verbose_name': 'RVT使用指南', 'verbose_name_plural': 'RVT使用指南'},
        ),
        migrations.RemoveIndex(
            model_name='rvtguide',
            name='rvt_guide_main_ca_2ca5cc_idx',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='sub_category',
        ),
        migrations.AddIndex(
            model_name='rvtguide',
            index=models.Index(fields=['main_category'], name='rvt_guide_main_ca_cf468b_idx'),
        ),
    ]
