# Generated by Django 5.2.6 on 2025-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_rvtguide_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrstoragebenchmark',
            name='test_datetime',
            field=models.DateTimeField(blank=True, help_text='進行測試的具體時間', null=True, verbose_name='測試時間'),
        ),
    ]
