# Generated by Django 5.2.6 on 2025-10-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_ocrstoragebenchmark_test_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rvtguide',
            options={'ordering': ['title'], 'verbose_name': 'RVT使用指南', 'verbose_name_plural': 'RVT使用指南'},
        ),
        migrations.RemoveIndex(
            model_name='rvtguide',
            name='rvt_guide_main_ca_cf468b_idx',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='main_category',
        ),
        migrations.RemoveField(
            model_name='rvtguide',
            name='question_type',
        ),
    ]
