# Generated by Django 5.2.6 on 2025-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_rvt_guide_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='超級管理員可以管理所有用戶的權限設定', verbose_name='超級管理員'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kb_ai_ocr',
            field=models.BooleanField(default=False, help_text='是否可使用知識庫版本的 AI OCR 功能', verbose_name='知識庫 AI OCR 權限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kb_protocol_rag',
            field=models.BooleanField(default=False, help_text='是否可使用知識庫版本的 Protocol RAG 功能', verbose_name='知識庫 Protocol RAG 權限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kb_rvt_assistant',
            field=models.BooleanField(default=False, help_text='是否可使用知識庫版本的 RVT Assistant 功能', verbose_name='知識庫 RVT Assistant 權限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='web_ai_ocr',
            field=models.BooleanField(default=False, help_text='是否可使用 Web 版本的 AI OCR 功能', verbose_name='Web AI OCR 權限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='web_protocol_rag',
            field=models.BooleanField(default=False, help_text='是否可使用 Web 版本的 Protocol RAG 功能', verbose_name='Web Protocol RAG 權限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='web_rvt_assistant',
            field=models.BooleanField(default=False, help_text='是否可使用 Web 版本的 RVT Assistant 功能', verbose_name='Web RVT Assistant 權限'),
        ),
    ]
