# Generated by Django 5.2.6 on 2025-10-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_userprofile_is_super_admin_userprofile_kb_ai_ocr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='會話ID')),
                ('guest_identifier', models.CharField(blank=True, max_length=255, verbose_name='訪客標識')),
                ('is_guest_session', models.BooleanField(default=False, verbose_name='是否為訪客會話')),
                ('chat_type', models.CharField(default='rvt_assistant_chat', max_length=50, verbose_name='聊天類型')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='對話標題')),
                ('summary', models.TextField(blank=True, verbose_name='對話摘要')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='訊息總數')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Token總使用量')),
                ('total_response_time', models.FloatField(default=0, verbose_name='總回應時間(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活躍')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已歸檔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='最後訊息時間')),
                ('auto_delete_at', models.DateTimeField(blank=True, null=True, verbose_name='自動刪除時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '對話會話',
                'verbose_name_plural': '對話會話',
                'db_table': 'conversation_sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='訊息ID')),
                ('role', models.CharField(choices=[('user', '用戶訊息'), ('assistant', 'AI回覆'), ('system', '系統訊息')], max_length=20, verbose_name='訊息角色')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('content_type', models.CharField(choices=[('text', '純文字'), ('markdown', 'Markdown'), ('json', 'JSON')], default='text', max_length=50, verbose_name='內容類型')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='順序號碼')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='回應時間(秒)')),
                ('token_usage', models.JSONField(blank=True, null=True, verbose_name='Token使用統計')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='信心分數')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元資料')),
                ('is_edited', models.BooleanField(default=False, verbose_name='是否已編輯')),
                ('original_content', models.TextField(blank=True, verbose_name='原始內容')),
                ('edit_history', models.JSONField(blank=True, null=True, verbose_name='編輯歷史')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='是否有幫助')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversationsession', verbose_name='所屬對話')),
            ],
            options={
                'verbose_name': '對話訊息',
                'verbose_name_plural': '對話訊息',
                'db_table': 'chat_messages',
                'ordering': ['conversation', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', '-created_at'], name='conv_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['session_id'], name='conv_session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['chat_type', 'is_active'], name='conv_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['-last_message_at'], name='conv_last_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['guest_identifier'], name='conv_guest_id_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'sequence_number'], name='msg_conv_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', '-created_at'], name='msg_role_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-created_at'], name='msg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['content'], name='msg_content_search_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('conversation', 'sequence_number')},
        ),
    ]
