# Generated by Django 5.2.6 on 2025-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_conversationsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='question_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='問題分類'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='satisfaction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='滿意度分數'),
        ),
    ]
