# Generated by Django 5.2.7 on 2025-10-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_analytics_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='對象ID')),
                ('title', models.CharField(blank=True, help_text='可選的圖片說明標題', max_length=200, null=True, verbose_name='圖片標題')),
                ('description', models.TextField(blank=True, help_text='可選的詳細描述', null=True, verbose_name='圖片描述')),
                ('filename', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('content_type_mime', models.CharField(max_length=100, verbose_name='MIME類型')),
                ('file_size', models.IntegerField(verbose_name='檔案大小(bytes)')),
                ('image_data', models.BinaryField(verbose_name='圖片資料')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='寬度')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度')),
                ('display_order', models.IntegerField(default=1, help_text='數字越小越前面', verbose_name='顯示順序')),
                ('is_primary', models.BooleanField(default=False, help_text='用於縮圖顯示等', verbose_name='是否為主要圖片')),
                ('is_active', models.BooleanField(default=True, help_text='停用的圖片不會在前端顯示', verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='內容類型')),
                ('rvt_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.rvtguide', verbose_name='關聯的 RVT Guide')),
            ],
            options={
                'verbose_name': '內容圖片',
                'verbose_name_plural': '內容圖片',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'display_order'], name='api_content_content_14a153_idx'), models.Index(fields=['content_type', 'object_id', 'is_active'], name='api_content_content_3958de_idx'), models.Index(fields=['rvt_guide', 'display_order'], name='api_content_rvt_gui_76f24f_idx'), models.Index(fields=['rvt_guide', 'is_active'], name='api_content_rvt_gui_97170a_idx'), models.Index(fields=['is_primary'], name='api_content_is_prim_c9ce8f_idx')],
            },
        ),
    ]
