# Generated by Django 5.2.7 on 2025-10-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_contentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Protocol 指南標題', max_length=300, verbose_name='標題')),
                ('protocol_name', models.CharField(db_index=True, help_text='例如：ULINK, Samsung, Apple Carplay', max_length=100, verbose_name='Protocol 名稱')),
                ('protocol_type', models.CharField(blank=True, help_text='例如：connectivity, data_transfer, authentication', max_length=50, verbose_name='Protocol 類型')),
                ('content', models.TextField(help_text='Protocol 的詳細說明', verbose_name='主要內容')),
                ('test_steps', models.TextField(blank=True, help_text='測試此 Protocol 的詳細步驟', verbose_name='測試步驟')),
                ('expected_result', models.TextField(blank=True, help_text='正確執行後的預期結果', verbose_name='預期結果')),
                ('common_issues', models.TextField(blank=True, help_text='測試過程中的常見問題和解決方案', verbose_name='常見問題')),
                ('category', models.CharField(blank=True, help_text='例如：車機測試, 手機連接, 音頻測試', max_length=100, verbose_name='分類')),
                ('difficulty', models.CharField(blank=True, choices=[('basic', '基礎'), ('intermediate', '中級'), ('advanced', '進階')], max_length=20, verbose_name='難度等級')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Protocol 測試指南',
                'verbose_name_plural': 'Protocol 測試指南',
                'db_table': 'protocol_guide',
                'ordering': ['protocol_name', 'title'],
                'indexes': [models.Index(fields=['protocol_name'], name='protocol_guide_name_idx'), models.Index(fields=['protocol_type'], name='protocol_guide_type_idx'), models.Index(fields=['category'], name='protocol_guide_category_idx')],
            },
        ),
    ]
