# Generated by Django 5.2.7 on 2025-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_protocolguide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolguide',
            options={'ordering': ['title'], 'verbose_name': 'Protocol 測試指南', 'verbose_name_plural': 'Protocol 測試指南'},
        ),
        migrations.RemoveIndex(
            model_name='protocolguide',
            name='protocol_guide_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='protocolguide',
            name='protocol_guide_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='protocolguide',
            name='protocol_guide_category_idx',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='common_issues',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='protocol_name',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='protocol_type',
        ),
        migrations.RemoveField(
            model_name='protocolguide',
            name='test_steps',
        ),
        migrations.AlterField(
            model_name='protocolguide',
            name='content',
            field=models.TextField(help_text='文檔的主要內容', verbose_name='文檔內容'),
        ),
        migrations.AlterField(
            model_name='protocolguide',
            name='title',
            field=models.CharField(help_text='文檔的顯示標題', max_length=300, verbose_name='文檔標題'),
        ),
    ]
