# Generated by Django 5.2.7 on 2025-10-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_protocolguide_options_and_more'),
    ]

    operations = [
    ]
