# Generated by Django 5.2.7 on 2025-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_protocol_guide_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kb_protocol_assistant',
            field=models.BooleanField(default=False, help_text='是否可使用知識庫版本的 Protocol Assistant 功能', verbose_name='知識庫 Protocol Assistant 權限'),
        ),
    ]
