# Generated by Django 5.2.7 on 2025-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_userprofile_kb_protocol_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='web_protocol_assistant',
            field=models.BooleanField(default=False, help_text='是否可使用 Web 版本的 Protocol Assistant 功能', verbose_name='Web Protocol Assistant 權限'),
        ),
    ]
