# Generated by Django 5.2.7 on 2025-10-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userprofile_web_protocol_assistant'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='protocol_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.protocolguide', verbose_name='關聯的 Protocol Guide'),
        ),
        migrations.AddIndex(
            model_name='contentimage',
            index=models.Index(fields=['protocol_guide', 'display_order'], name='api_content_protoco_aed4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='contentimage',
            index=models.Index(fields=['protocol_guide', 'is_active'], name='api_content_protoco_4fedcb_idx'),
        ),
    ]
