# Generated by Django 5.2.7 on 2025-11-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_add_protocol_guide_to_content_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_type', models.CharField(choices=[('protocol_assistant', 'Protocol Assistant'), ('rvt_assistant', 'RVT Assistant')], help_text='要設定 threshold 的 Assistant', max_length=50, unique=True, verbose_name='Assistant 類型')),
                ('master_threshold', models.DecimalField(decimal_places=2, default=0.7, help_text='段落向量搜尋使用的 threshold (0.00 ~ 1.00)。其他搜尋會自動計算：文檔=0.85倍、關鍵字=0.5倍', max_digits=3, verbose_name='主 Threshold')),
                ('description', models.TextField(blank=True, help_text='此設定的用途說明', null=True, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用此設定', verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, help_text='最後更新此設定的使用者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '搜尋 Threshold 設定',
                'verbose_name_plural': '搜尋 Threshold 設定',
                'db_table': 'search_threshold_settings',
                'ordering': ['assistant_type'],
            },
        ),
    ]
