# Generated by Django 5.2.7 on 2025-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_multi_vector_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage1_content_weight',
            field=models.IntegerField(default=40, help_text='段落向量搜尋時的內容權重（0-100）', verbose_name='第一階段內容權重'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage1_threshold',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='段落向量搜尋的相似度閾值（0.00-1.00）', max_digits=3, verbose_name='第一階段 Threshold'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage1_title_weight',
            field=models.IntegerField(default=60, help_text='段落向量搜尋時的標題權重（0-100）', verbose_name='第一階段標題權重'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage2_content_weight',
            field=models.IntegerField(default=50, help_text='全文向量搜尋時的內容權重（0-100）', verbose_name='第二階段內容權重'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage2_threshold',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='全文向量搜尋的相似度閾值（0.00-1.00，建議比第一階段低）', max_digits=3, verbose_name='第二階段 Threshold'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage2_title_weight',
            field=models.IntegerField(default=50, help_text='全文向量搜尋時的標題權重（0-100）', verbose_name='第二階段標題權重'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='use_unified_weights',
            field=models.BooleanField(default=True, help_text='若啟用，第一、二階段使用相同權重（向後相容模式）', verbose_name='使用統一權重'),
        ),
        migrations.AlterField(
            model_name='searchthresholdsetting',
            name='content_weight',
            field=models.IntegerField(default=40, help_text='內容向量的權重百分比（0-100），保留以向後相容。建議使用 stage1/stage2 配置', verbose_name='內容權重（舊）'),
        ),
        migrations.AlterField(
            model_name='searchthresholdsetting',
            name='title_weight',
            field=models.IntegerField(default=60, help_text='標題向量的權重百分比（0-100），保留以向後相容。建議使用 stage1/stage2 配置', verbose_name='標題權重（舊）'),
        ),
    ]
