# Generated by Django 5.2.7 on 2025-11-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_searchthresholdsetting_stage1_content_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusage',
            name='chat_type',
            field=models.CharField(choices=[('know_issue_chat', 'Protocol RAG'), ('log_analyze_chat', 'AI OCR'), ('rvt_assistant_chat', 'RVT Assistant'), ('protocol_assistant_chat', 'Protocol Assistant')], max_length=50, verbose_name='聊天類型'),
        ),
    ]
