# Generated by Django 5.2.7 on 2025-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_unified_benchmark_test_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='context_mode',
            field=models.CharField(choices=[('hierarchical', '層級結構'), ('adjacent', '線性視窗'), ('both', '兩者兼具')], default='hierarchical', help_text='hierarchical=父子段落, adjacent=前後段落, both=全部', max_length=20, verbose_name='上下文模式'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='context_window',
            field=models.IntegerField(default=0, help_text='搜尋時前後各擴展幾個段落（0=不擴展，1-5）', verbose_name='視窗擴展大小'),
        ),
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='include_siblings',
            field=models.BooleanField(default=False, help_text='是否包含同層級的兄弟段落', verbose_name='包含兄弟段落'),
        ),
    ]
