# Generated by Django 5.2.7 on 2025-12-03 10:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_context_window_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage1_rrf_k',
            field=models.IntegerField(default=60, help_text='RRF 融合常數（30-120）。較小值讓頂部結果更突出；較大值讓結果更平均。業界標準: 60', verbose_name='一階段 RRF K 值'),
        ),
        migrations.AlterField(
            model_name='difyconfigversion',
            name='dify_api_url',
            field=models.CharField(default=api.models.get_default_dify_api_url, max_length=500, verbose_name='Dify API URL'),
        ),
    ]
