# Generated by Django 5.2.7 on 2025-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_stage1_rrf_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchthresholdsetting',
            name='stage1_post_boost_threshold',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Title Boost 加分後的二次過濾閾值（0.00-1.00）。建議設為比第一次低，避免過濾掉相關但標題不完全匹配的結果', max_digits=3, verbose_name='一階段 Boost 後 Threshold'),
        ),
    ]
