# Generated by Django 5.2.7 on 2025-12-21 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_stage1_post_boost_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕'), ('suspended', '已停用')], default='approved', help_text='帳號審核狀態', max_length=20, verbose_name='帳號狀態'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='application_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請部門'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='application_reason',
            field=models.TextField(blank=True, null=True, verbose_name='申請理由'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒絕原因'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='審核時間'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_users', to=settings.AUTH_USER_MODEL, verbose_name='審核者'),
        ),
    ]
