#!/bin/bash
# Protocol Guide Markdown 編輯器 - 圖片預覽修復測試腳本

echo "=========================================="
echo "Protocol Guide 圖片預覽修復測試"
echo "=========================================="
echo ""

echo "📋 修復內容摘要："
echo "  1. 移除 SSR 渲染（renderToStaticMarkup）"
echo "  2. 使用 markdown-it 生成基礎 HTML"
echo "  3. 添加客戶端 JavaScript 異步加載圖片"
echo "  4. 圖片直接使用 API 端點 URL"
echo ""

echo "🔧 修改的檔案："
echo "  - frontend/src/components/editor/MarkdownEditorLayout.jsx"
echo "    * renderMarkdownWithImages 函數（Lines 220-256）"
echo "    * 新增 useEffect 處理圖片加載（Lines 442-490）"
echo ""

echo "🧪 測試步驟："
echo ""
echo "步驟 1: 訪問 Protocol Guide 編輯頁面"
echo "  URL: http://10.10.172.127/knowledge/protocol-guide/markdown-edit/76"
echo "  （或任何其他有圖片的 Protocol Guide）"
echo ""

echo "步驟 2: 在編輯器中輸入圖片引用"
echo "  範例："
echo "  # 測試圖片顯示"
echo "  [IMG:32]"
echo "  [IMG:35]"
echo "  [IMG:36]"
echo ""

echo "步驟 3: 檢查右側預覽面板"
echo "  ✅ 預期結果："
echo "    - 圖片應該正常顯示"
echo "    - 圖片有 1px 綠色邊框（#52c41a）"
echo "    - 圖片可以正常縮放"
echo ""
echo "  ❌ 如果失敗："
echo "    - 檢查瀏覽器開發者工具 Console（F12）"
echo "    - 查看是否有 fetch 錯誤"
echo "    - 確認圖片 ID 存在（參考下方列表）"
echo ""

echo "📊 可用測試圖片 ID："
echo "  - 32: 1.jpg (922 × 669)"
echo "  - 35: 2.jpg (755 × 566)"
echo "  - 36: 3.jpg (931 × 566)"
echo "  - 37: 4.jpg (1005 × 566)"
echo "  - 38: 5.jpg (794 × 566)"
echo ""

echo "🔍 技術細節："
echo ""
echo "修復前的問題："
echo "  • 使用 renderToStaticMarkup 進行 SSR 渲染"
echo "  • CustomImage 組件的 useEffect 不執行"
echo "  • 無法異步加載圖片數據"
echo "  • 顯示「圖片載入失敗」錯誤"
echo ""

echo "修復後的實現："
echo "  1. renderHTML 返回基礎 HTML（包含 data-image-id 屬性）"
echo "  2. useEffect 監聽 formData.content 變化"
echo "  3. 查找所有 img.content-image-preview 元素"
echo "  4. 對每個圖片執行 fetch 請求"
echo "  5. 將 data_url 設置為 img.src"
echo "  6. 成功：綠色邊框，失敗：紅色邊框 + 錯誤訊息"
echo ""

echo "📝 相關文檔："
echo "  - docs/features/protocol-guide-image-preview-implementation.md"
echo "  - frontend/src/components/editor/MarkdownEditorLayout.jsx"
echo "  - frontend/src/pages/DevMarkdownTestPage.js（參考實現）"
echo ""

echo "✅ 測試完成後請確認："
echo "  1. 圖片可以正常顯示"
echo "  2. 沒有紅色錯誤邊框"
echo "  3. Console 沒有錯誤訊息"
echo "  4. 多張圖片可以同時顯示"
echo ""

echo "=========================================="
echo "開始測試！"
echo "=========================================="
